user nginxuser;
worker_processes auto;
pid /srv/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Temp directories
    client_body_temp_path /srv/cache/client_temp;
    proxy_temp_path       /srv/cache/proxy_temp;
    fastcgi_temp_path     /srv/cache/fastcgi_temp;
    uwsgi_temp_path       /srv/cache/uwsgi_temp;
    scgi_temp_path        /srv/cache/scgi_temp;

    include /etc/nginx/conf.d/*.conf;
}
